import 'package:flutter/material.dart';

import '../../app_session.dart';
import '../../ui/merka_theme_tokens.dart';
import '../security/action_permission.dart';
import '../../sector_publico/security/roles_permisos_service.dart';
import 'command_registry.dart';

List<CommandDefinition> defaultContextualCommands() => [
  CommandDefinition(
    id: 'hrm.leave.approve',
    label: 'Aprobar ausencia seleccionada',
    description: 'Aprueba la solicitud de ausencia del empleado en contexto.',
    icon: Icons.check_circle,
    color: Colors.green,
    moduleId: 'hrm',
    permissionModuleId: 'hrm',
    requiredAction: AppAction.approve,
    contextType: 'hrm_leave',
    actionKey: 'approve',
    priority: 100,
    contextual: true,
    handler: (context, active) => active.action('approve')!(context, active),
  ),
  CommandDefinition(
    id: 'hrm.leave.reject',
    label: 'Rechazar ausencia seleccionada',
    description: 'Solicita el motivo y rechaza la ausencia en contexto.',
    icon: Icons.cancel,
    color: Colors.red,
    moduleId: 'hrm',
    permissionModuleId: 'hrm',
    requiredAction: AppAction.approve,
    contextType: 'hrm_leave',
    actionKey: 'reject',
    priority: 99,
    contextual: true,
    handler: (context, active) => active.action('reject')!(context, active),
  ),
  CommandDefinition(
    id: 'mrp.work_order.start',
    label: 'Iniciar producción',
    description: 'Valida stock y pasa la Work Order a en proceso.',
    icon: Icons.play_arrow,
    color: MerkaThemeTokens.navy600,
    moduleId: 'mrp',
    permissionModuleId: 'mrp',
    requiredAction: AppAction.update,
    contextType: 'mrp_work_order',
    actionKey: 'start',
    priority: 100,
    contextual: true,
    handler: (context, active) => active.action('start')!(context, active),
  ),
  CommandDefinition(
    id: 'mrp.work_order.complete',
    label: 'Completar Work Order',
    description: 'Registra producción terminada y mueve el producto final.',
    icon: Icons.task_alt,
    color: Colors.green,
    moduleId: 'mrp',
    permissionModuleId: 'mrp',
    requiredAction: AppAction.update,
    contextType: 'mrp_work_order',
    actionKey: 'complete',
    priority: 90,
    contextual: true,
    handler: (context, active) => active.action('complete')!(context, active),
  ),
  CommandDefinition(
    id: 'mrp.work_order.bom',
    label: 'Ver BOM de Work Order',
    description: 'Abre la estructura de materiales de la orden activa.',
    icon: Icons.account_tree,
    color: MerkaThemeTokens.gold500,
    moduleId: 'mrp',
    permissionModuleId: 'mrp',
    requiredAction: AppAction.view,
    contextType: 'mrp_work_order',
    actionKey: 'bom',
    priority: 80,
    contextual: true,
    handler: (context, active) => active.action('bom')!(context, active),
  ),
  CommandDefinition(
    id: 'crm.opportunity.advance',
    label: 'Avanzar oportunidad',
    description: 'Mueve la oportunidad a su siguiente etapa permitida.',
    icon: Icons.trending_up,
    color: MerkaThemeTokens.navy600,
    moduleId: 'crm_pipeline',
    permissionModuleId: 'crm',
    requiredAction: AppAction.managePipeline,
    contextType: 'crm_opportunity',
    actionKey: 'advance',
    priority: 100,
    contextual: true,
    handler: (context, active) => active.action('advance')!(context, active),
  ),
  CommandDefinition(
    id: 'public.budget.create_appropriation',
    label: 'Crear apropiación',
    description: 'Abre el formulario de nueva apropiación presupuestal.',
    icon: Icons.add_chart,
    color: MerkaThemeTokens.navy600,
    moduleId: 'presupuesto_publico',
    permissionLabel: 'Acceso a presupuesto público',
    contextType: 'presupuesto_publico',
    actionKey: 'create_appropriation',
    priority: 100,
    contextual: true,
    authorize: (_) => AppSession.puedeAbrirModuloId('presupuesto_publico'),
    handler: (context, active) =>
        active.action('create_appropriation')!(context, active),
  ),
  CommandDefinition(
    id: 'public.budget.create_cdp',
    label: 'Expedir CDP',
    description: 'Abre el formulario para expedir un CDP.',
    icon: Icons.verified,
    color: MerkaThemeTokens.navy600,
    moduleId: 'presupuesto_publico',
    permissionLabel: 'Permiso.expedirCDP',
    contextType: 'presupuesto_publico',
    actionKey: 'create_cdp',
    priority: 90,
    contextual: true,
    authorize: (_) => AppSession.puedeEjecutarPermiso(Permiso.expedirCDP),
    handler: (context, active) => active.action('create_cdp')!(context, active),
  ),
  CommandDefinition(
    id: 'public.budget.create_rp',
    label: 'Expedir RP',
    description: 'Abre el formulario para expedir un RP.',
    icon: Icons.assignment_turned_in,
    color: MerkaThemeTokens.navy600,
    moduleId: 'presupuesto_publico',
    permissionLabel: 'Permiso.expedirRP',
    contextType: 'presupuesto_publico',
    actionKey: 'create_rp',
    priority: 80,
    contextual: true,
    authorize: (_) => AppSession.puedeEjecutarPermiso(Permiso.expedirRP),
    handler: (context, active) => active.action('create_rp')!(context, active),
  ),
];
